# Generated by Django 2.2.16 on 2020-09-15 07:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ADVENTURE', 'Adventure'), ('FAMILY', 'Family'), ('FANTASY', 'Fantasy'), ('MUSICAL', 'Musical'), ('ACTION', 'Action'), ('SciFi', 'Sci-Fi'), ('DRAMA', 'Drama'), ('WAR', 'War'), ('HORROR', 'Horror'), ('MYSTERY', 'Mystery'), ('THRILLER', 'Thriller'), ('ROMANCE', 'Romance'), ('ANIMATION', 'Animation'), ('CRIME', 'Crime'), ('COMEDY', 'Comedy')], max_length=16), blank=True, null=True, size=None)),
                ('director', models.CharField(max_length=20)),
                ('imdb_score', models.PositiveIntegerField(null=True)),
                ('popularity', models.PositiveIntegerField(null=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
