# Generated by Django 2.2.16 on 2020-09-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Select genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='popularity',
            field=models.IntegerField(null=True),
        ),
    ]
